### ISSUE TITLE
napari-hub website lacks documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [zacsimile/napari-pymeshlab#3]
Hi @zacsimile ,

the [napari-hub page](https://www.napari-hub.org/plugins/napari-pymeshlab) of the plugin lacks documentation. If you delete `.napari/description.md` and push an update to pypi, then the readme.md will be shown.

If you're busy, I'm happy to send a PR :-)

Best,
Robert

**Comment by zacsimile** [comment]
Thanks for the heads up. I have been neglecting this a bit. I just want to extend the functionality you added to points as well and then I'll release a new version. I'll get to it this week. :)

**Comment by zacsimile** [comment]
I changed my mind, I'll get to the points stuff later. Updated in e2125567952ab05779e6d763e59539964df3ce68.

**Comment by zacsimile** [comment]
Appears to be fixed, except the image doesn't come through. Any ideas how to fix that, @haesleinhuepf?
